title: My Awesome Blog
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/jekyll-theme-kagami"
lang: en # site language (en/ja/zh-Hans/zh-Hant)
color_scheme: github # this specifies color scheme for syntax highlighting
github_username: kamikat
twitter_username: kamikat_bot
instagram_username: kamikat_bot

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
